import { PrismaClient, ExhibitionStatus } from "@prisma/client";

const prisma = new PrismaClient();

const exhibitions = [
  {
    slug: "archive-in-focus",
    title: "Archive in Focus",
    subtitle: "Manuscripts and archival records from the museum's collection",
    category: "Archive & Manuscripts",
    dateRange: "Ongoing",
    location: "Level Four · Floor 3",
    imageSrc: "/images/gallery-floor3-archive.webp",
    imageAlt: "The top-floor gallery: display cases of manuscripts and framed historic photographs around the lantern opening",
    descriptionHeading: "About the Exhibition",
    description: "On the top floor of the tower, the museum's gallery for temporary and changing exhibitions currently draws on its own archive: manuscripts and archival records that document Ladakh's social, cultural and historical past.\n\nSeen after the objects on the floors below, they add the people, places and events behind the collection, and record how life in Leh and the wider region has changed.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Selected documents from the museum's archive, showing contracts, permits and trade correspondence from the late 19th and early 20th centuries.",
    curator: "The museum team",
    status: ExhibitionStatus.Current,
    badgeLabel: "Now on",
    featuredOnHome: true,
    seoKeywords: ["Archive in Focus", "Central Asian Museum", "Ladakh manuscripts", "Silk Road documents"],
    createdAt: new Date("2026-10-01T12:00:00.000Z"),
  },
  {
    slug: "threads-of-the-silk-road",
    title: "Threads of the Silk Road",
    subtitle: "Textiles and costume that travelled the caravan routes into Ladakh.",
    category: "Textiles",
    dateRange: "14/06/2026 – 30/07/2026",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/textiles.webp",
    imageAlt: "Woven textiles from the collection",
    descriptionHeading: "About the Exhibition",
    description: "Textiles and costume that travelled the caravan routes into Ladakh. Featuring silk brocades, woollen robes, dyed sashes, and embroidered garments worn across the trading centres of Central Asia and the Himalayas.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Clothing and textiles were among the most portable and valuable commodities traded across the high passes. This exhibition gathers historic garments that illustrate cross-cultural tailoring traditions, weaving techniques, and decorative patterns.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Silk Road textiles", "Central Asian costume", "Ladakh textiles"],
    createdAt: new Date("2026-06-14T00:00:00.000Z"),
  },
  {
    slug: "the-caravan-kitchen",
    title: "The Caravan Kitchen",
    subtitle: "Cooking vessels, utensils and the everyday life of trading households in Leh.",
    category: "Utensils & Household",
    dateRange: "02/03/2026 – 18/04/2026",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/utensils.webp",
    imageAlt: "Brass and copper utensils",
    descriptionHeading: "About the Exhibition",
    description: "Cooking vessels, utensils and the everyday life of trading households in Leh. A focused look at the brass, copper, and ironware carried by travellers and used in traditional Ladakhi kitchens.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Hospitality on the caravan trails was central to survival and social cohesion. This selection highlights portable stoves, churns for butter tea, ladles, and serving dishes that furnished caravan stops and Leh hearths.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Caravan Kitchen", "Ladakhi kitchen", "Copper utensils"],
    createdAt: new Date("2026-03-02T00:00:00.000Z"),
  },
  {
    slug: "saddles-and-long-roads",
    title: "Saddles and Long Roads",
    subtitle: "Riding gear and travel equipment from the routes over the Karakoram.",
    category: "Travel & Equipment",
    dateRange: "10/11/2025 – 15/01/2026",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/saddle.webp",
    imageAlt: "A decorated saddle",
    descriptionHeading: "About the Exhibition",
    description: "Riding gear and travel equipment from the routes over the Karakoram. Displays decorated wooden and leather saddles, stirrups, bridles, and pack bags engineered for unforgiving mountain terrain.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Horses, mules, and yaks carried the trade across the highest passes on earth. The saddlery reflects master leatherwork, metal inlay, and wool padding developed over generations of caravan journeys.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Caravan saddles", "Karakoram trail", "Travel gear"],
    createdAt: new Date("2025-11-10T00:00:00.000Z"),
  },
  {
    slug: "coins-weights-and-trade",
    title: "Coins, Weights and Trade",
    subtitle: "How goods were measured, weighed and paid for in the markets of Leh.",
    category: "Trade & Commerce",
    dateRange: "01/08/2025 – 20/09/2025",
    location: "Central Asian Museum, Leh",
    imageSrc: "/images/objects/trade.webp",
    imageAlt: "Objects of trade",
    descriptionHeading: "About the Exhibition",
    description: "How goods were measured, weighed and paid for in the markets of Leh. Showcases silver and copper coins from Kashmir, Yarkand, Tibet, and British India, alongside balance scales and commercial seals.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Trade across borders required multilingual accountants and trusted standards of measurement. These instruments and currencies recount the economic vibrancy of Leh's historic bazaar.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Coins and weights", "Leh market", "Silk route trade currency"],
    createdAt: new Date("2025-08-01T00:00:00.000Z"),
  },
  {
    slug: "faith-and-pilgrimage",
    title: "Faith and Pilgrimage",
    subtitle: "Religious objects that tell of shared Buddhist traditions and pilgrim journeys.",
    category: "Religious Objects",
    dateRange: "05/05/2025 – 30/06/2025",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/religious.webp",
    imageAlt: "Religious objects",
    descriptionHeading: "About the Exhibition",
    description: "Religious objects that tell of shared Buddhist traditions and pilgrim journeys. Statuary, prayer wheels, amulets, and ritual instruments preserved by families and monastic institutions across Ladakh.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Trade routes were equally pathways of spiritual exchange. Pilgrims carried portable reliquaries, texts, and sacred representations connecting shrines from Mount Kailash to Leh and Lhasa.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Buddhist art", "Pilgrimage Ladakh", "Religious artefacts"],
    createdAt: new Date("2025-05-05T00:00:00.000Z"),
  },
  {
    slug: "written-records",
    title: "Written Records",
    subtitle: "Manuscripts and letters that document the region's history.",
    category: "Manuscripts",
    dateRange: "12/02/2025 – 31/03/2025",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/manuscripts.webp",
    imageAlt: "Manuscripts from the archive",
    descriptionHeading: "About the Exhibition",
    description: "Manuscripts and letters that document the region's history. Archival documents in Tibetan, Persian, Urdu, and Arabic preserving decrees, merchant agreements, and personal letters.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "The written legacy of the Trans-Himalayan crossroads reveals formal alliances and everyday transactions. Paper varieties, calligraphy styles, and seals provide clues to provenance and international diplomacy.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Tibetan manuscripts", "Urdu decrees", "Trans-Himalayan archives"],
    createdAt: new Date("2025-02-12T00:00:00.000Z"),
  },
  {
    slug: "metalwork-of-the-crossroads",
    title: "Metalwork of the Crossroads",
    subtitle: "Ewers, bowls and lamps made and traded across Central Asia.",
    category: "Metalwork",
    dateRange: "20/10/2024 – 30/11/2024",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/metalwork.webp",
    imageAlt: "Metal vessels",
    descriptionHeading: "About the Exhibition",
    description: "Ewers, bowls and lamps made and traded across Central Asia. An examination of chased copper, repoussé silver, and cast brass pieces combining Persian, Kashmiri, and Central Asian decorative motifs.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Metal smiths across Central Asia and northern India traded designs and techniques. The vessels in this gallery display floral tracery, calligraphic inscriptions, and animal handles specific to caravan trade hubs.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Central Asian metalwork", "Copper ewers", "Ladakh craftsmanship"],
    createdAt: new Date("2024-10-20T00:00:00.000Z"),
  },
  {
    slug: "building-the-tower",
    title: "Building the Tower",
    subtitle: "Photographs of the museum's construction by Ladakhi masons and carpenters.",
    category: "Architecture & History",
    dateRange: "03/07/2024 – 25/08/2024",
    location: "Central Asian Museum, Leh",
    imageSrc: "/images/thf/timber-frame.webp",
    imageAlt: "The tower's timber frame under construction",
    descriptionHeading: "About the Exhibition",
    description: "Photographs of the museum's construction by Ladakhi masons and carpenters. Documenting the hand-carved timber framework, granite masonry, and local craftsmanship guided by André Alexander and THF/LOTI.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Built entirely by hand using traditional stone, mud, and timber, the museum building is itself a premier artefact. This photographic documentation records the artisans whose skill brought the fortress tower to life.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Museum construction", "Tibet Heritage Fund", "André Alexander"],
    createdAt: new Date("2024-07-03T00:00:00.000Z"),
  },
  {
    slug: "tools-of-the-trade",
    title: "Tools of the Trade",
    subtitle: "Craft tools from workshops in Leh and the villages around it.",
    category: "Tools & Craft",
    dateRange: "15/04/2024 – 31/05/2024",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/tools.webp",
    imageAlt: "Craft tools",
    descriptionHeading: "About the Exhibition",
    description: "Craft tools from workshops in Leh and the villages around it. Woodworking adzes, blacksmithing hammers, leather awls, and stone chisels that sustained centuries of craftsmanship in Ladakh.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Traditional building and tool-making skills were preserved through apprenticeship. These handmade implements showcase the resourcefulness and precision of village artisans.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Craft tools", "Ladakh workshops", "Traditional carpentry"],
    createdAt: new Date("2024-04-15T00:00:00.000Z"),
  },
  {
    slug: "old-photographs-of-leh",
    title: "Old Photographs of Leh",
    subtitle: "Historic photographs of the town, its market and its people.",
    category: "Photographs",
    dateRange: "01/01/2024 – 28/02/2024",
    location: "Level Four · Floor 3",
    imageSrc: "/images/objects/photographs.webp",
    imageAlt: "Historic photographs",
    descriptionHeading: "About the Exhibition",
    description: "Historic photographs of the town, its market and its people. Archival prints from the late 19th and early 20th centuries showing the main bazaar, caravan caravanserais, and mountain passes.",
    curatorialEssayHeading: "Curatorial Narrative & Historical Context",
    curatorialEssay: "Early photography in Ladakh captured the crossroads in transition. This collection offers a visual record of Leh's streetscapes, historic architecture, and the diverse traders who met in the town center.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Historic Leh photographs", "Bazaar Ladakh", "Caravan photography"],
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    slug: "preview-photographs-2011",
    title: "Photographic Exhibition at the Preview Opening",
    subtitle: "When the museum first opened to the public for a special preview, its first artefacts were shown with a photographic exhibition.",
    category: "Photographs & History",
    dateRange: "23–24 August 2011",
    location: "Central Asian Museum, Leh",
    imageSrc: "/images/museum-garden-exterior.webp",
    imageAlt: "The museum tower in the Tsas Soma Garden",
    descriptionHeading: "About the Exhibition",
    description: "On 23 and 24 August 2011, the Central Asian Museum opened to the public for a special preview. Alongside its first artefacts, visitors saw a photographic exhibition.",
    curatorialEssayHeading: "Historical Context",
    curatorialEssay: "When the museum first opened to the public for a special preview, its first artefacts were shown with a photographic exhibition.",
    curator: "The museum team",
    status: ExhibitionStatus.Permanent,
    badgeLabel: "Past exhibition",
    featuredOnHome: false,
    seoKeywords: ["Preview Opening 2011", "Central Asian Museum", "Historic Photographs"],
    createdAt: new Date("2011-08-23T00:00:00.000Z"),
  },
];

async function main() {
  console.log("Seeding 12 exhibitions from CAM into database...");

  // Delete test records if any that don't belong
  const allowedSlugs = exhibitions.map((e) => e.slug);
  await prisma.exhibition.deleteMany({
    where: {
      slug: {
        notIn: allowedSlugs,
      },
    },
  });

  for (const ex of exhibitions) {
    await prisma.exhibition.upsert({
      where: { slug: ex.slug },
      update: {
        title: ex.title,
        subtitle: ex.subtitle,
        category: ex.category,
        dateRange: ex.dateRange,
        location: ex.location,
        imageSrc: ex.imageSrc,
        imageAlt: ex.imageAlt,
        descriptionHeading: ex.descriptionHeading,
        description: ex.description,
        curatorialEssayHeading: ex.curatorialEssayHeading,
        curatorialEssay: ex.curatorialEssay,
        curator: ex.curator,
        status: ex.status,
        badgeLabel: ex.badgeLabel,
        featuredOnHome: ex.featuredOnHome,
        seoKeywords: ex.seoKeywords,
        createdAt: ex.createdAt,
      },
      create: {
        slug: ex.slug,
        title: ex.title,
        subtitle: ex.subtitle,
        category: ex.category,
        dateRange: ex.dateRange,
        location: ex.location,
        imageSrc: ex.imageSrc,
        imageAlt: ex.imageAlt,
        descriptionHeading: ex.descriptionHeading,
        description: ex.description,
        curatorialEssayHeading: ex.curatorialEssayHeading,
        curatorialEssay: ex.curatorialEssay,
        curator: ex.curator,
        status: ex.status,
        badgeLabel: ex.badgeLabel,
        featuredOnHome: ex.featuredOnHome,
        seoKeywords: ex.seoKeywords,
        createdAt: ex.createdAt,
      },
    });
    console.log(`Upserted: ${ex.title} (${ex.slug})`);
  }

  const count = await prisma.exhibition.count();
  console.log(`Finished! Total exhibitions in database: ${count}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
